name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/summary-tasks-bot:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USER }}/summary-tasks-bot:latest
            docker stop summary-tasks-bot|| true
            docker rm summary-tasks-bot|| true
            docker run -d --restart unless-stopped \
              --name summary-tasks-bot \
              -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
              -e OPENAI_TOKEN=${{ secrets.OPENAI_TOKEN }} \
              -e OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              ${{ secrets.DOCKERHUB_USER }}/summary-tasks-bot:latest
